import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/header";
import Footer from "@/components/footer";
import ChatbotWindow from "@/components/chatbot-window";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="bg-bg h-full flex flex-col">
        <Header/>
        <div className="flex-grow">
          {children}
        </div>
        <ChatbotWindow/>
        <Footer/>
      </body>
    </html>
  );
}